### ISSUE TITLE
Make Handlebars external dependency

### ISSUE THREAD

**Issue by fhemberger** [guybedford/hbs#3]
Instead of keeping your own copy of Handlebars, it should be listed in your bower/volo/etc config as dependency. Also, a recent PR to Handlebars adds AMD support: https://github.com/wycats/handlebars.js/pull/537

**Comment by guybedford** [comment]
Yeah it was exactly for the AMD support.... although there still needs to be a careful distinction between the inclusion of the Handlebars runtime and the full module. I will look into this deeper if I find the time.

Just a note - this module isn't officially maintained, and was more experimental at the time. There are a lot of features that are missing that should be here, and it was more of a project for myself, since the existing Handlebars plugin was too complicated to install. It is a great seed to build a better handlebars plugin though, and I was kind of hoping SlexAxton would take it as a pull request to improve the official one.

**Comment by fhemberger** [comment]
So why don't you maintain it? I think it's looks like a nice and clean solution. So far I've been using Alex' solution but it is not maintained at the moment as well and parts of it are outdated and a bit bloated. I was looking into your code to use as a simpler replacement.

For distinguishing between handlebars.js and handlebars.runtime.js, this could be simply archived with a different path configuration or a pragma exclude for development and production build in require.js itself.

**Comment by guybedford** [comment]
I may well... it seems like it could be worthwhile. But I need to "finish" the work first (it is just a very basic initial prototype)! I may have some time for this in the next few weeks, but at the moment it is just tricky to justify the time commitment.
